
export const HANDLE_GROUP_DATA = "HANDLE_GROUP_DATA"
export const HANDLE_CARD_DATA = "HANDLE_CARD_DATA"
export const HANDLE_ADD_CARD_DATA = "HANDLE_ADD_CARD_DATA"
export const HANDLE_EDIT_CARD_DATA = "HANDLE_EDIT_CARD_DATA"
export const GET_CARD_DATA = "GET_CARD_DATA"
export const DELETE_CARD_DATA = "DELETE_CARD_DATA";

export const GET_DATA = "GET_DATA";
export const REQUEST_DATA = "REQUEST_DATA";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const DELETE_DATA_SUCCESS = "DELETE_DATA_SUCCESS";
export const GET_DATA_FAILURE = "GET_DATA_FAILURE";
